### ISSUE TITLE
Add features

### ISSUE THREAD

**Issue by Chjango** [freshautomations/telegram-moderator-bot#1]
- /help command lists the commands that a mod would use
- add /warn to warn a user who has violated conduct within the chatroom
- track the number of warns a user has been given
- if a user has been warned a second time, they are automatically banned
- remove /hello command

**Comment by greg-szabo** [comment]
1. Remove /hello command.
2. Create /help command.
3. Create /warn command ; ban after two warns.
4. Fix /unban command kicking out moderators.

**Comment by greg-szabo** [comment]
Also make the bot less chatty: it shouldn't politely ask to type /hello when someone types the wrong command.

**Comment by greg-szabo** [comment]
Done in 0.2
